In [7]:
import numpy as np

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
[1,2,3,5,7,12]

[1, 2, 3, 5, 7, 12]

In [11]:
a = np.array([1,2,3,5,7,12])

In [12]:
a

array([ 1,  2,  3,  5,  7, 12])

In [13]:
a[2]

3

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
# Muliti-dimentional array

In [17]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# list of lists

In [19]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
n[0,1] # n[0][1]

2

In [22]:
n[:,1]

array([2, 5, 8])

In [23]:
# Randomly generated arrays
np.random.rand(5,2) # 5 rows, 2 columns

array([[0.35030915, 0.94310731],
       [0.96199663, 0.78503468],
       [0.67848695, 0.31174979],
       [0.57705482, 0.38761584],
       [0.02643523, 0.24132282]])

In [24]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [25]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [26]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [27]:
# Element-wise opeartions
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a + 1

array([1, 2, 3, 4, 5])

In [29]:
a * 2

array([0, 2, 4, 6, 8])

In [30]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [31]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [32]:
# Comparison operations
a >= 2

array([False, False,  True,  True,  True])

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a > b

array([False, False,  True,  True,  True])

In [36]:
# get the elements in a that are greater in b:
a[a > b]

array([2, 3, 4])

In [37]:
# Summarizing operations
a

array([0, 1, 2, 3, 4])

In [38]:
a.sum()

10

In [39]:
a.min()

0

In [40]:
a.mean()

2.0

In [41]:
n.std()

2.581988897471611

In [42]:
# Multiplication

In [43]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result
    

In [44]:
u = np.array([2,4,5,6])

In [46]:
v = np.array([1,0,0,2])

In [47]:
vector_vector_multiplication(u,v)

14.0

In [48]:
u.dot(v)

14

In [50]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    result result
    

In [ ]:
U = np.arrange(
    [2,4,5,6],
    [],
    []
)